import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <footer className="mt-10 bg-brand-primary text-white w-full aspect-video flex flex-col items-center justify-end p-4">
        <p className="italic self-end">See you space cowboy...</p>
      </footer>
    </html>
  );
}
